### ISSUE TITLE
The demo does not work as the demo image shows

### ISSUE THREAD

**Issue by aqasoft** [Matthias1590/ConsoleDraw#2]
Hi! The demo code you posted leaves succesive screeens with the following text: 
`←[0;0f  `
before each print. 
Working on W10, with Python 3.9.

**Comment by aqasoft** [comment]
Happened with the previous example (the sinus wave) and with the current one (clock).

**Comment by Matthias1590** [comment]
The demo was recorded on Windows 10 using Python 3.9 so that's odd.. Seems like an issue with the terminal you're running the program in. Could you record your vs code terminal?

**Comment by aqasoft** [comment]
Hi Matthias! Following is your request, a fresh terminal and calling the sample code file straight from there:

![2022-01-14_09-51-43](https://user-images.githubusercontent.com/8036233/149518616-ad67de9c-4d56-4c30-8d7d-e709b13f53fb.gif)

**Comment by aqasoft** [comment]
Hi Matthias! Yes indeed, I am sending you two recordings, the first, as you asked, from VScode internal terminal and the second one from an external terminal just calling the demo file without any obtrusions. 

1: 
![2022-01-14_10-04-03](https://user-images.githubusercontent.com/8036233/149519894-7892ca81-9b5b-4999-a4a8-4602e65d12af.gif)

and 2:
![2022-01-14_09-51-43](https://user-images.githubusercontent.com/8036233/149519929-a2a5fd6f-0852-4ba9-86e3-1747394a556a.gif)

**Comment by Matthias1590** [comment]
Thanks for reporting this! I was unaware that the module did not work in the windows command prompt and I'll try to find a way to make it work there too, I'll let you know when this is solved.

**Comment by Matthias1590** [comment]
I just released version 2.4.0, it should be fixed (if it is, please close this issue :)), thanks again for reporting this!

**Comment by aqasoft** [comment]
Hi Matthias, I cannot install the new release of ConsoleDraw nor build it from a local repo clone:

Installing directly from GIT since normal pip install consoledraw brings v3.x:

```
> pip install git+https://github.com/Matthias1590/ConsoleDraw.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/Matthias1590/ConsoleDraw.git
  Cloning https://github.com/Matthias1590/ConsoleDraw.git to c:\users\rango\appdata\local\temp\pip-req-build-b9wx8ixk
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RANGO\\AppData\\Local\\Temp\\pip-req-build-b9wx8ixk\\setup.py'"'"'; __file__='"'"'C:\\Users\\RANGO\\AppData\\Local\\Temp\\pip-req-build-b9wx8ixk\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\RANGO\AppData\Local\Temp\pip-pip-egg-info-x2f6pnmy'
         cwd: C:\Users\RANGO\AppData\Local\Temp\pip-req-build-b9wx8ixk\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\RANGO\AppData\Local\Temp\pip-req-build-b9wx8ixk\setup.py", line 13, in <module>
        long_description=readme(),
      File "C:\Users\RANGO\AppData\Local\Temp\pip-req-build-b9wx8ixk\setup.py", line 6, in readme
        return f.read()
      File "c:\program files\python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 890: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Or trying to run setup.py from my desktop:

```
d:\Users\RANGO\Documents\GitHub\ConsoleDraw>py setup.py build
Traceback (most recent call last):
  File "d:\Users\RANGO\Documents\GitHub\ConsoleDraw\setup.py", line 13, in <module>
    long_description=readme(),
  File "d:\Users\RANGO\Documents\GitHub\ConsoleDraw\setup.py", line 6, in readme
    return f.read()
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 890: character maps to <undefined>
```

Really glad I can be of help in any way that you think.

**Comment by Matthias1590** [comment]
Should be fixed now, thanks for letting me know!

**Comment by aqasoft** [comment]
It installs properly now! 
However:
1. It continues to work flawlessly in VScode's integrated terminal.
2. It looks much better, but it jumps up and down and skips seconds (back and forth) in CMD. Take a close look to the seconds in the image:

![2022-01-14_21-48-26](https://user-images.githubusercontent.com/8036233/149602259-72bc5545-9fdb-4d69-a222-eacfc34b4cdc.gif)

**Comment by Matthias1590** [comment]
Is that in cmd or in the python console? I believe there is a difference between the two and it worked for me in cmd, haven't tested it in the python console yet tho

**Comment by aqasoft** [comment]
It's not the Python Console. It is a standard CMD console, I've tried opening it in Admin mode, resizing fonts, many options.
I've even tried the sample code directly from ConEmu, and it produces the same effect as shown in the last gif.

I've just also tried with another PC, Python v3.10.0, W10 up-to-date, standard CMD console and the effect is the same.

I think maybe you should try in a clean VM? Maybe your testing environment is using some non-standard additional piece of software.

**Comment by Matthias1590** [comment]
Very odd, it behaves like that for me in the Python console but works in CMD. I tried testing on a vm and it gave me the expected result, could you show me what it looks like in the Python console?

**Comment by aqasoft** [comment]
I have two tests to report:

**1. Python IDLE console**. Fails when executing the demo code with the following output info:

```
>>> 
======================= RESTART: D:\_devpy\test\test1.py =======================
Traceback (most recent call last):
  File "D:\_devpy\test\test1.py", line 5, in <module>
    console = Console()
  File "C:\Program Files\Python39\lib\site-packages\consoledraw\console.py", line 19, in __init__
    self.update()
  File "C:\Program Files\Python39\lib\site-packages\consoledraw\console.py", line 72, in update
    grid = self.__generate_grid()
  File "C:\Program Files\Python39\lib\site-packages\consoledraw\console.py", line 31, in __generate_grid
    size = os.get_terminal_size()
ValueError: bad file descriptor
>>> 
```
screen capture:

![Clipboard01](https://user-images.githubusercontent.com/8036233/149681270-8e23a0d9-767d-4a19-b2d4-3391ad1fbf01.jpg)

**2. Tested on a brand new fresh and clean install of W10Pro** (old version: 1909) on VMware. The only SW added was GIT and Python 3.10.1. 
ConsoleDraw was installed using the GIT repository, having the CMD console both in Admin mode and normal user mode (the target folder for the installations is different).

It produces the same result of the digital watch jumping up and down one line and the seconds skipping back and forth one second. Sorry to report this one, I really expected a different result.

original screen capture of the observed behavior:

![2022-01-14_21-48-26](https://user-images.githubusercontent.com/8036233/149602259-72bc5545-9fdb-4d69-a222-eacfc34b4cdc.gif)

**Comment by Matthias1590** [comment]
Might take me a while to figure this one out, I'll keep you updated and do my best though.
